# Generated by Django 4.1.5 on 2023-05-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesAndLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_top', models.ImageField(upload_to='Images/logo-top/')),
                ('logo_footer', models.ImageField(upload_to='Images/logo-footer/')),
                ('banner', models.ImageField(upload_to='Images/banner-home/')),
            ],
        ),
    ]
