# Generated by Django 4.1.5 on 2023-05-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessWeb', '0004_testinomials'),
    ]

    operations = [
        migrations.AddField(
            model_name='testinomials',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
