# Generated by Django 4.1.5 on 2023-05-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessWeb', '0005_testinomials_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testinomials',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
