# Generated by Django 4.1.5 on 2023-05-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessWeb', '0006_alter_testinomials_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testinomials',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
