# Generated by Django 4.1.5 on 2023-05-22 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessWeb', '0007_alter_testinomials_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='testinomials',
            new_name='Testimonials',
        ),
    ]
