# Generated by Django 4.1.5 on 2023-06-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessWeb', '0008_rename_testinomials_testimonials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='Images/banner-home/')),
            ],
        ),
        migrations.DeleteModel(
            name='ImagesAndLogo',
        ),
    ]
