# Generated by Django 4.2.2 on 2023-07-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessWeb', '0009_banner_delete_imagesandlogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popup', models.ImageField(upload_to='Images/popup-home/')),
            ],
        ),
    ]
